---
title:  |
        | Pre-Analysis Plan:
        | Casting the First Stone: Understanding Attitudes towards Lynching in Brazil
author:
  - Danilo Freire[^freire]
  - David Skarbek[^skarbek]
date: \today
abstract: "Why do citizens resort to extrajudicial violence? While vigilantism has significantly decreased in advanced democracies, lynchings continue to be common practice in many developing nations. In this pre-analysis plan, we propose three survey experiments to investigate (i) who are the potential lynching victims, (ii) how citizens justify mob violence, and (iii) whether information provision can reduce support for vigilantism. First, we will run a conjoint experiment to assess which victim characteristics are associated with higher likelihood of lynching. Then we will show respondents a short news article about a real lynching episode and ask them whether they perceive the motivations of the lynch mob as legitimate. Lastly, we test whether providing information about legal punishment for lynching perpetrators, human rights guarantees, and the risk of retribution makes respondents less likely to endorse extralegal violence. We will run the experiments in Brazil, a country which has seen a sharp rise in vigilante attacks and currently experiences one lynching attempt per day. Our survey will be conducted online and include 1,000 participants."
abstractspacing: double
keywords: Brazil, crime, extralegal violence, lynching, vigilantism
fontsize: 12pt
margin: 2cm
urlcolor: darkblue
linkcolor: Mahogany
citecolor: Mahogany
spacing: double
papersize: a4paper
bibliography: references.bib
biblio-style: apalike
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    number_sections: yes
    keep_tex: no
    toc: no
    toc_depth: 3
    template: template.latex
---

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# If you need to install any package while knitting the document
r <- getOption("repos")
r["CRAN"] <- "https://cran.rstudio.com/"
options(repos = r)
if (!require("kableExtra")) {
    install.packages("kableExtra")
}
```

[^freire]: Postdoctoral Research Associate, The Political Theory Project, Brown University, 8 Fones Alley, Providence, RI 02912, [`danilofreire@gmail.com`](mailto:danilofreire@gmail.com), <https://danilofreire.github.io>.

[^skarbek]: The Department of Political Science and the Political Theory Project, Brown University, 8 Fones Alley, Providence, RI 02912, USA, [`david_skarbek@brown.edu`](mailto:david_skarbek@brown.edu), <http://davidskarbek.com>.

\newpage

# Motivation
\label{sec:motivation}

\doublespacing

Why do citizens resort to extralegal punishment?[^definitions] Although mob
violence has decreased in advanced democracies, vigilantism remains widespread
in the developing world. In particular, Latin America has been severely affected
by a recent increase in lynchings. Motivated by growing numbers of drug-related
crime and by police ineffectiveness, citizen violence has surged in the region
[@mallen2014vigilantes]. Brazil provides a telling example. From 2011 to 2015,
the country registered about 2,500 lynching episodes, and in 2015 alone 173
people were killed by angry mobs, an average of one execution every two days
[@barbara2015vigilantes; @zechmeister2014political]. According to José Martins,
who has studied lynchings in Brazil for more than 30 years, those figures are
not only the highest in the country's history, but also the highest in the world
[@pearson2018latam]. Victims are generally accused of petty theft, and many are
beaten to death for stealing mobile phones, cooking utensils, or pairs of
sandals [@barbara2015vigilantes]. Lynching perpetrators are often young men, but
they also include female teenagers, elderly women, and even members of local
police forces [@oliveira2016mob].

[^definitions]: Here we consider extralegal violence, vigilantism, lynching,
and related terms as synonyms. We follow @moncada2017varieties [6] and define
vigilantism as "the collective use or threat of extralegal violence in
response to an alleged criminal act". While we focus here on vigilantism that
directly involves physical violence, we make no distinction between lethal and
non-lethal lynching episodes.

Recent research suggests that support for vigilantism in Latin America is
associated with exposure to violence [@garcia2019anger], untrustworthy law
enforcement [@zizumbo2017community], perceived insecurity [@ceobanu2011crime;
@godoy2004justice], and social inequality [@arias2010violent]. However, approval
for extrajudicial violence raises important questions about the relationship
between states and societies in the region. First, while vigilantism provides
social order to vulnerable populations, it also undermines the legitimacy of
state institutions [@schuberth2013challenging]. Lynching episodes reinforce the
idea that civilians should not wait for legal proceedings and that social
control is better exerted by the people themselves [@black1983crime]. Second,
victim characteristics greatly impact the likelihood and severity of lynchings.
In Brazil, a person is rarely lynched when they commit a crime against males,
and females that commit the same crimes as males also receive less
punishment.[^fapesp] Moreover, there is no significant social difference between
victims and perpetrators, nor black Brazilians are particularly targeted by
lynch mobs [@oliveira2016mob]. These dynamics pose a puzzle to existing
explanations for mob violence support and stand in sharp contrast with the
American experience [@smaangs2016doing; @tolnay1995festival; @wood2011lynching].

[^fapesp]: See
<https://revistapesquisa.fapesp.br/en/mob-injustice>. Access: June, 2020.

In this study, we endeavour to answer the following questions: 1) which victim
characteristics increase individual support for extralegal punishment?; 2) how
do individuals justify their approval for vigilantism?; and 3) can information
provision reduce support for mob violence? We design a set of three experiments
to tackle these issues. Our first experiment consists of a conjoint analysis
where we present respondents with different profiles of lynching victims and ask
them which individual they believe deserved the punishment. In our second
experiment, we test how ineffective policing, slow criminal justice systems,
and demand for hasher punishment for criminals affect individual propensity to
support mob violence. Finally, we assess whether citizens who support
extrajudicial killings change their opinions when informed about the legal
consequences of lynchings, constitutional human rights, or the risk of
_vendettas_ associated with mob violence.

# Experiment 01
\label{sub:exp01}

We start our analysis with a choice-based conjoint experimental design. Each
respondent will be shown ten pairs of lynching victims. Each profile will
consist of five attributes: 1) crime perpetrator; 2) race of the crime
perpetrator; 3) offense; 4) victim of the motivating crime; 5) lynching
perpetrators. The levels in each attribute are available in table
\ref{tab:categories} below. They will be randomised in the experiment. Each
respondent will read a short description of the survey experiment and we will
ask them to choose the profile in which lynching seems less justified. We phrase
the experiment in negative terms (who should _not_ be lynched) to protect
subjects from making the uncomfortable choice of actively selecting a lynching
victim.

\begin{table}[htpb]
\small
\begin{center}
\caption{\textbf{Attributes and Levels}}
\label{tab:categories}
\begin{tabular}{l !{\vrule width 1pt}p{9cm}}
\Xhline{2\arrayrulewidth}
\textbf{Attribute} & \multicolumn{1}{c}{\textbf{Levels}} \\
\Xhline{2\arrayrulewidth}
\footnotesize
Crime perpetrator & Adult male; adult female; male teenager; female teenager; elderly man; elderly woman \\
\\
Race & Black; white; native Brazilian; Asian \\
\\
Offense & Picks the pocket; steals the car; molests; rapes; murders \\
\\
Crime victim & Adult male; adult female; male child; female child; male teenager; female teenager; elderly man; elderly woman\\
\\
Lynching perpetrators & Bystanders; acquaintances; the family of the victim;
police\\
\Xhline{2\arrayrulewidth}
\end{tabular}
\end{center}
\end{table}

\newpage

Respondents are also required to rate each profile on a scale from 1
to 7, where 1 indicates they definitely believe lynching was not justified
and 7 indicates they definitely believe lynching was justified. We take this
measure as a robustness check for our main experimental estimate.

Before each profile pair, respondents will read the following
message:

* Lynching is often used as social punishment in Brazil. We are interested in
  knowing more about how Brazilians see these episodes. In the next ten
  questions, please read the description of two possible lynching victims in
  Brazil and indicate in which case you believe the punishment is _less_
  justified.[^portuguese]

[^portuguese]: The text will be displayed in Portuguese. The translation is as
follows: Linchamento é por vezes usado como punição social no Brasil. Estamos
interessados em saber mais sobre como os brasileiros vêem estes episódios. Nas
próximas cinco questões, por favor, leia a descrição de duas possíveis vítimas
de linchamento no Brasil e indique em quais delas você acredita que a punição
é _menos_ justificada.


## Sample
\label{sub:sample}

We invite respondents from all regions of Brazil to participate in our
experiment. Qualtrics will recruit 1,000 adult Brazilian citizens to take part
in our survey experiment.

We will also include 15 questions on demographics that we believe may influence
the results. The questions are: 1) the respondent's age, 2) gender, 3) state of
birth, 4) state they currently live in, 5) ethnicity, 6) level of education, 7)
religion (if any), 8) monthly family income in minimum wages, 9) political
orientation (left to right), 10) support for death penalty, 11) whether they had
been victimised in the last year, 12) whether they believe crime has worsened,
13) whether they believe militias improve law and order, 14) trust in the
police, 15) trust in the judicial system.

## Estimation
\label{sub:estimation}

We will estimate our models with the `cregg` package [@leeper2018cregg] for the
R statistical language [@rstats2019]. We will report marginal means instead of
average marginal conditional effects (AMCE) of attitudes towards lynchings.
@leeper2018subgroup show that AMCEs can be misleading in subgroup analysis as
model results are sensitive to the choice of reference categories in
interactions. In contrast, marginal means provide a clear description of
quantities of interest, in our case preferences towards lynching, while allowing
for easy comparisons between groups of respondents. Their interpretation is also
straightforward: a 50% marginal means estimate represents that respondents are
indifferent when a given attribute appears vis-à-vis other attributes. When the
coefficient is lower than 50%, respondents dislike profiles with that attribute.
Conversely, when the point estimate is higher than 50%, respondents prefer
profiles containing a given attribute. We will cluster standard errors by
respondent.

## Hypotheses
\label{sec:hypotheses}

We expect that, on average, respondents will select profiles with the following
characteristics:

1) Crime perpetrator: male teenager
2) Race: blacks
3) Offense: murder
4) Victim: female child
5) Lynching perpetrators: the family of the victim

We also expect that punishment will be lower for females of any age, whites
and Asians, pick pocketers, and if the victim of the motivating crime is male.
Additionally, we expect that respondents see lynchings as less legitimate if
they are carried out by bystanders and the police forces. We have no prior
beliefs about the size of each coefficient.

## Heterogeneous Effects
\label{sub:het01}

We will also run subgroup comparisons in our sample. We hypothesise that
attitudes towards lynching vary according to age, gender, race, level of
education, political ideology, and previous victimisation. In particular, we
hypothesise that:

* Younger respondents believe that lynchings by the police are less justified.

* Female respondents believe that lynchings against females are less justified.

* Respondents of a particular race are less likely to choose individuals of
  the same race as lynching victims.

* More educated individuals show less support for lynchings against petty
  criminals.

* Political ideology has no effect on support for lynchings when the victim is
  female.

* Right-wingers show stronger support for lynchings against males than
  left-wingers.

* Respondents who were victimised in the last year are more likely to support
  lynchings by bystanders and the police.

# Experiment 02

In our second experiment, we will measure how respondents justify their
support for extralegal violence. We test the effect of three explanations for
lynching in Brazil: 1) police ineffectiveness; 2) slow criminal justice; 3)
demand for harsher punishment for criminals. Below, we discuss these hypotheses
in further detail.

Research shows that police ineffectiveness frequently appears as a strong
predictor for vigilantism [@cruz2019determinants; @garcia2019anger]. The direct
result of the weakness of police institutions is that citizens decide to take
criminal matters "in their own hands", thus persecuting and punishing the
criminals by themselves. A recent statistic indicates that the police
solves only 10% of the homicides in Brazil, what lends evidence to the link
between weak law enforcement and lynchings [@pearson2018latam].

Another aspect that is often suggested in the literature is that vigilantism
rises where citizens have little faith in courts. Most commonly, this is due to
delays in the criminal justice administration, which makes criminals stay at
large for many years. In Brazil, the penal code allows the accused to appeal
each decision several times, so it can take decades before a criminal case is
closed [@sousa2005utilizaccao]. In this respect, citizens do not believe that,
even if the criminal is put to trial, he/she will be punished in a timely
matter. Note that although the police is part of the criminal justice system, we
separate the two institutions in our experiment. This is because respondents may
not associate the two, mainly when it comes to legal procedures against
lawbreakers.

Lastly, we evaluate whether respondents believe that the legal punishment
assigned to criminals is not proportional to the severity of the crimes. In
particular, we hope to gauge the demand for iron-fisted criminal justice in
Brazil. Although this treatment arm is related to the previous ones, it
questions not the efficiency of the institutions, but their legitimacy. We
believe that the demand for harsher laws is on the rise in Brazil, and this may
be a major reason why citizens justify their support for mob violence.
In fact, Brazilians are often vocal about their preference for repressive legal
punishment. After having his son murdered by a local thug, a bar owner told the
Wall Street Journal that "_even if he had been put behind bars for 100 years it
wouldn't have been enough to pay for all his crimes_" [@pearson2018latam]. We
hypothesise that this feeling is widespread in the population.

The experiment consists of three treatment conditions and one control group.
Respondents will read a short excerpt of a news article describing a real
lynching case, which will be slightly edited so that respondents have no prior
knowledge of the crime.[^jornal] The vignette for the control group includes no
information about the reasons behind the lynching. We will ask respondents
to show their level of support for mob violence using a 0-100 slider, where 0
means no support and 100 means full support. Respondents in each of the three
treatment arms will read the same piece, but with one additional sentence
explaining the motivation of the lynch mob. The vignettes are as follows:

[^jornal]: The original article is available at the following address:
<http://folhadeibitinga.com.br/materia/5543/suspeito-de-estuprar-menina-e-linchado-e-morto-em-jau>.
Access: June 2020.

* *Control group*: A young man between 20 and 25 years old was lynched and
  killed on the 1\textsuperscript{st} of June. He was accused of raping an
  11-year-old girl in São Paulo. He was clubbed to death by about 20 residents
  who heard the girl screaming after she was taken to an empty lot and forced
  to have sex with him at gunpoint.[^control-exp02]

[^control-exp02]: In Portuguese: Um jovem entre 20 e 25 anos foi linchado e
morto no dia primeiro de junho. Ele foi acusado de estuprar uma menina de 11
anos em São Paulo. Ele foi atacado e morto à pauladas por cerca de 20 moradores
que ouviram a menina gritar após ela ter sido levada para um terreno baldio e
forcada a ter relações sexuais com ele sob ameaça de morte.

* *Treatment 01 - Police ineffectiveness*: A young man between 20 and 25
  years old was lynched and killed on the 1\textsuperscript{st} of June. He was
  accused of raping an 11-year-old girl in São Paulo. He was clubbed to death
  by about 20 residents who heard the girl screaming after she was taken to an
  empty lot and forced to have sex with him at gunpoint. **One of the
  residents who took part in the lynching said they did so because "the police
  never patrols the area"**.[^treat01-exp02]

[^treat01-exp02]: In Portuguese: Um jovem entre 20 e 25 anos foi linchado e
morto no dia primeiro de junho. Ele foi acusado de estuprar uma menina de 11
anos em São Paulo. Ele foi atacado e morto à pauladas por cerca de 20 moradores
que ouviram a menina gritar após ela ter sido levada para um terreno baldio e
forçada a ter relações sexuais com ele sob ameaça de morte. **Um dos moradores
envolvidos no linchamento disse que eles fizeram isso porque "a polícia nunca
patrulha o local".**

* *Treatment 02 - Criminal justice ineffectiveness*: A young man between 20
  and 25 years old was lynched and killed on the 1\textsuperscript{st} of June.
  He was accused of raping an 11-year-old girl in São Paulo. He was clubbed to
  death by about 20 residents who heard the girl screaming after she was taken
  to an empty lot and forced to have sex with him at gunpoint. **One of the
  residents who took part in the lynching said they did so because "the
  judicial system is too slow"**.[^treat02-exp02]

[^treat02-exp02]: In Portuguese: Um jovem entre 20 e 25 anos foi linchado e
morto no dia primeiro de junho. Ele foi acusado de estuprar uma menina de 11
anos em São Paulo. Ele foi atacado e morto à pauladas por cerca de 20 moradores
que ouviram a menina gritar após ela ter sido levada para um terreno baldio e
forçada a ter relações sexuais com ele sob ameaça de morte. **Um dos moradores
envolvidos no linchamento disse que eles fizeram isso porque "a justiça é muito
lenta"**.

* *Treatment 03 - Demand for harsher legal punishment*: A young man between 20
  and 25 years old was lynched and killed on the 1\textsuperscript{st} of June.
  He was accused of raping an 11-year-old girl in São Paulo. He was clubbed to
  death by about 20 residents who heard the girl screaming after she was taken
  to an empty lot and forced to have sex with him at gunpoint. **One of the
  residents who took part in the lynching said they did so because "the
  judicial punishment is not harsh enough"**.[^treat03-exp02]

[^treat03-exp02]: In Portuguese: Um jovem entre 20 e 25 anos foi linchado e
morto no dia primeiro de junho. Ele foi acusado de estuprar uma menina de 11
anos em São Paulo. Ele foi atacado e morto à pauladas por cerca de 20 moradores
que ouviram a menina gritar após ela ter sido levada para um terreno baldio e
forcada a ter relações sexuais com ele sob ameaça de morte. **Um dos moradores
envolvidos no linchamento disse que eles fizeram isso porque "a punição da
justiça não é dura o suficiente"**.

Before each vignette, respondents will read the following text:

* You will be shown a news article. Please read it carefully. After you read
  the article, we will ask one question about it.[^vig01-exp02]

[^vig01-exp02]: In Portuguese: Uma notícia será apresentada para você. Por favor,
leia a notícia com atenção. Após você ler o artigo, faremos uma pergunta sobre
ele.

After the vignette, respondents will be presented with this question:

* Would you think that the lynching was justified? Please use the slider below
  to indicate your opinion. For disagreement, use 0 to 49; for agreement,
  use 51 to 100. Please use 50 if you neither agree nor
  disagree.[^vig02-exp02]

[^vig02-exp02]: In Portuguese: Você acha que o linchamento foi correto? Por
favor, use a barra abaixo para indicar sua opinião. Para discordar, use de 0 a
49; para concordar, use de 51 a 100. Por favor, use 50 para não concordar nem
discordar.

## Sample

We will randomise the treatment and control conditions to the entire respondent
pool. The randomisation procedure here is independent of that of the previous
experiment.

## Estimation

We will carry out our hypothesis tests with OLS. We will compare the average
score given by the control group with the average score attributed by
respondents in each treatment condition. We will use robust standard errors for
all the models.

## Hypotheses

On average, we expect that:

\vspace{.5cm}

\noindent _H1_: Respondents assigned to the _police ineffectiveness_ treatment
group will show stronger support for lynchings when compared to the control
group. We believe that the effect will be smaller than for the other two
treatment conditions.

\vspace{.3cm}

\noindent _H2_: Respondents assigned to the _criminal justice ineffectiveness_
treatment group will show stronger support for lynchings when compared to the
control group. We hypothesise that the effect for this group will be higher
than that of the first treatment condition but lower than that of the third
treatment group.

\vspace{.3cm}

\noindent _H3_: Respondents assigned to the _demand for harsher punishment_
treatment group will show the strongest support for lynchings.

## Heterogeneous Effects

We hypothesise that these respondents are more likely to agree that lynchings
are justified:

1) Older citizens
2) White
3) Low levels of education
4) Right-wingers
5) Had been previously victimised

# Experiment 03

Our last experiment aims to measure the effect of information provision on
attitudes about lynching. More specifically, we will test whether reminding
respondents about the legal and social consequences of mob violence reduces
the subjects' level of support for such practice.

The experiment has three treatment conditions plus a control group. In all of
them we will present respondents with a short statement affirming that some
Brazilians support vigilantism under certain conditions. The control group will
be asked to rate their agreement with the statement with a 0-100 slider where
100 indicates full agreement with the statement and 0 indicates no agreement.
Respondents will be asked to use 0 to 49 if they disagree, 50 if they neither
agree nor disagree, and 50-100 if they agree with the sentence.

Each of the three treatment groups will receive a different message about the
legal or social consequences of lynching in Brazil. In the first treatment
arm, we will inform subjects about how the Brazilian constitution and penal code
punishes civilian violence. The second treatment group will be notified about
the human rights guarantees enshrined in Brazil's legal framework. The last
group will read a vignette that mentions how lynchings can spark _vendettas_ and
initiate a cycle of violence in the community. Subjects in the control group
will receive no information about the consequences of lynchings. The text shown
to the control and treatment groups can be read below.

* *Control group*: In Brazil, some people believe that lynching may be
  justified under certain conditions. To what degree do you agree or disagree
  that lynching can be justified? Please use the slider below to indicate your
  preference. For disagreement, use 0 to 49; for agreement, use 51 to 100.
  Please use 50 if you neither agree nor disagree.[^control-exp03]

[^control-exp03]: In Portuguese: No Brasil, algumas pessoas acreditam que
linchamentos são justificados sob certas condições. O quanto você concorda ou
discorda que linchamentos podem ser justificados? Por favor, use a barra abaixo
para indicar sua preferência. Para indicar que discorda, use de 0 a 49; para
concordar, use de 51 a 100. Por favor, use 50 caso você não concorde nem
discorde.

* *Treatment 01 - Legal punishment for lynching perpetrators*: In Brazil,
  some people believe that lynching may be justified under certain conditions.
  **However, the Brazilian constitution and penal code strictly forbid
  lynching and those involved can be accused of torture or murder**. To what
  degree do you agree or disagree that lynching can be justified? Please use
  the slider below to indicate your preference. For disagreement, use 0 to 49;
  for agreement, use 51 to 100. Please use 50 if you neither agree nor
  disagree.[^treat01-exp03]

[^treat01-exp03]: In Portuguese: No Brasil, algumas pessoas acreditam que
linchamentos são justificados sob certas condições. **Entretanto, a
constituição e o código penal do Brasil proíbem estritamente os linchamentos e
os envolvidos podem ser acusados de tortura ou assassinato.** O quanto você
concorda ou discorda que linchamentos podem ser justificados? Por favor, use a
barra abaixo para indicar sua preferência. Para indicar que discorda, use de 0
a 49; para concordar, use de 51 a 100. Por favor, use 50 caso você não concorde
nem discorde.

* *Treatment 02 - Human rights*: In Brazil, some people believe that lynching
  may be justified under certain conditions. **However, the Brazilian
  constitution states that all individuals have the right of not being
  tortured, including criminals**. To what degree do you agree or disagree that
  lynching can be justified? Please use the slider below to indicate your
  preference. For disagreement, use 0 to 49; for agreement, use 51 to 100.
  Please use 50 if you neither agree nor disagree.[^treat02-exp03]

[^treat02-exp03]: In Portuguese: No Brasil, algumas pessoas acreditam que
linchamentos são justificados sob certas condições. **Entretanto, a
constituição do Brasil afirma que todos os indivíduos têm o direito de não
serem torturados, inclusive criminosos**. O quanto você concorda ou discorda que
linchamentos podem ser justificados? Por favor, use a barra abaixo para indicar
sua preferência. Para indicar que discorda, use de 0 a 49; para concordar, use
de 51 a 100. Por favor, use 50 caso você não concorde nem discorde.

* *Treatment 03 - Vendettas*: In Brazil, some people believe that lynching
  may be justified under certain conditions. **However, lynchings can trigger
  a new cycle of violence as the family or friends of the victim may retaliate
  the community**. To what degree do you agree or disagree that lynching can be
  justified? Please use the slider below to indicate your preference. For
  disagreement, use 0 to 49; for agreement, use 51 to 100. Please use 50 if you
  neither agree nor disagree.[^treat03-exp03]

[^treat03-exp03]: In Portuguese: No Brasil, algumas pessoas acreditam que
linchamentos são justificados sob certas condições. **Entretanto, linchamentos
podem iniciar um ciclo de violência pois a família ou amigos da vítima podem
retaliar a comunidade**. O quanto você concorda ou discorda que linchamentos
podem ser justificados? Por favor, use a barra abaixo para indicar sua
preferência. Para indicar que discorda, use de 0 a 49; para concordar, use de
51 a 100. Por favor, use 50 caso você não concorde nem discorde.

## Sample

We will randomise the treatment and control conditions to all subjects included
in our sample. The treatment assignment here is independent of that of the
previous two experiments.

## Estimation

We are interested in the difference between the average score assigned by each
of the treatment groups minus the average score assigned by the control group.
We will estimate average treatment effects using OLS with dummy indicators for
the treatment groups.

## Hypotheses

In this experiment, we test the following hypotheses:

\vspace{.5cm}

\noindent _H1_: Providing information about the criminal consequences of
lynchings reduces individual support for vigilantism.

\vspace{.3cm}

\noindent _H2_: Reminding respondents that torture violates human rights does
not decrease their support for vigilantism.

\vspace{.3cm}

\noindent _H3_: Information about _vendettas_ decrease individual support for
vigilantism.

\vspace{.5cm}

These three hypotheses will allow us to test how respondents react to different
consequences of extralegal legal and, hopefully, also help policy-makers design
more effective campaigns against vigilantism in Brazil.

## Heterogeneous Effects

As with the previous two experiments, we will measure whether our treatments
have heterogeneous effects. The same demographic characteristics we describe
above -- age, gender, race, education level, political ideology, and previous
victimisation -- will also be used here.

\setlength{\parindent}{0cm}
\setlength{\parskip}{5pt}
